### ISSUE TITLE
New multiselect breaks when using multiple package files

### ISSUE THREAD

**Issue by HitkoDev** [raineorshine/npm-check-updates#1151]
- [X] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [X] I am using the latest version of `npm-check-updates`
- [X] I am using `node >= 14`

---

## Steps to Reproduce

.ncurc:

```js
{
    "packageFile": [
        "package.json",
        "packages/*/package.json"
    ]
}
```

Steps:

- run ncu
- toggle items

## Current Behavior

Works for the first package, all other packages throw

`TypeError: Cannot read properties of undefined (reading 'disabled')`

## Expected Behavior

No error.

**Comment by raineorshine** [comment]
Hi, thanks for reporting. I ran `ncu -i` with multiple package files and I did not get any errors. 

Can you provide your complete `.ncurc` file and `dependencies` list so I can recreate the repo and try to reproduce?

My setup:

```sh
$ cat package.json
{
  "dependencies": {
	  "ncu-test-v2": "2.0.0"
  }
}
$ cat a/package.json
{
  "dependencies": {
	  "ncu-test-tag": "1.1.0"
  }
}
$ cat b/package.json
{
  "dependencies": {
	  "ncu-test-return-version": "2.0.0"
  }
}
```

ncu -i:

```
$ ncu -i
Using config file /Users/raine/projects/ncu-issues/1151/.ncurc
Upgrading /Users/raine/projects/ncu-issues/1151/package.json
[====================] 1/1 100%

✔ Choose which packages to update ›

 ncu-test-v2  1.0.0  →  2.0.0

Run npm install to install new versions.

Upgrading /Users/raine/projects/ncu-issues/1151/a/package.json
[====================] 1/1 100%

✔ Choose which packages to update ›

All dependencies match the desired package versions :)

Run npm install to install new versions.

Upgrading /Users/raine/projects/ncu-issues/1151/b/package.json
[====================] 1/1 100%

? Choose which packages to update › Space to deselect. Enter to upgrade.
❯ ◉ ncu-test-return-version  1.0.0  →  2.0.0

ncu-test-return-version  1.0.0  →  2.0.0

Run npm install to install new versions.
```

**Comment by HitkoDev** [comment]
You get the error when you try to toggle updates in second / third / ... package.json

**Comment by HitkoDev** [comment]
[https://codesandbox.io/s/old-flower-jvex98](https://codesandbox.io/s/old-flower-jvex98)

Run `ncu -i` and try toggling all dependencies.

```
Using config file /sandbox/.ncurc
Upgrading /sandbox/package.json
[====================] 3/3 100%

✔ Choose which packages to update ›

All dependencies match the desired package versions :)

Run npm install to install new versions.

Upgrading /sandbox/packages/a/package.json


No dependencies.
Upgrading /sandbox/packages/b/package.json
[====================] 1/1 100%

? Choose which packages to update › Space to deselect. Enter to upgrade.
❯ ◉ rimraf  1.0.0  →  3.0.2readline.js:1280
            throw err;
            ^

TypeError: Cannot read property 'disabled' of undefined
    at MultiselectPrompt.renderDoneOrInstructions (/sandbox/node_modules/prompts-ncu/lib/elements/multiselect.js:256:33)
    at MultiselectPrompt.render (/sandbox/node_modules/prompts-ncu/lib/elements/multiselect.js:272:12)
    at MultiselectPrompt.up (/sandbox/node_modules/prompts-ncu/lib/elements/multiselect.js:119:10)
    at ReadStream.keypress (/sandbox/node_modules/prompts-ncu/lib/elements/prompt.js:32:16)
    at ReadStream.emit (events.js:412:35)
    at emitKeys (internal/readline/utils.js:358:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1270:36)
    at ReadStream.emit (events.js:412:35)
    at addChunk (internal/streams/readable.js:293:12)
error Command failed with exit code 1.
```

**Comment by raineorshine** [comment]
Thanks! I was able to reproduce from your demo.

Fixed and published in `v15.0.1`.

**Comment by HitkoDev** [comment]
Thanks, seems to work fine now.

**Comment by HitkoDev** [comment]
You get error when you try to toggle updates.
