### ISSUE TITLE
--workspace option under windows seems to be not working

### ISSUE THREAD

**Issue by grbd** [raineorshine/npm-check-updates#1240]
- [ X ] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [ X ] I am using the latest version of `npm-check-updates`
- [ X ] I am using `node >= 14.14`

---

Hi,
As a result of https://github.com/raineorshine/npm-check-updates/issues/1239
I think I've discovered that the --workspace option doesn't work under windows.

`--workspaces` (selecting all of them from the root) seems to work fine.
But `--workspace packagename` seems to just exit without doing anything / without displaying any kind of error so I suspect it's not finding the workspace.

I tried running some tests against version v16.5.1 and the latest v16.5.3 to see if the recent changes had made a difference, but it seems to be the same regardless. I think the github workflows are only setup to test against ubuntu.

Running `npm install` `npm build` `npm test`

The tail end of the output is:
```
  staticRegistry
    ✔ latest


  341 passing (7m)
  3 pending
  7 failing

  1) --deep
       ignore stdin if --packageFile glob is specified:

      AssertionError: expected '1' to not equal '1'
      + expected - actual


      at Context.<anonymous> (test\deep.test.ts:84:51)

  2) --deep
       update multiple packages:

      AssertionError: expected '1' to not equal '1'
      + expected - actual


      at Context.<anonymous> (test\deep.test.ts:103:52)

  3) --workspace
       update single workspace with --workspace:
     AssertionError: expected {} to have property 'packages/a/package.json'
      at Context.<anonymous> (test\workspaces.test.ts:239:26)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

  4) --workspace
       update single workspace with -w:
     AssertionError: expected {} to have property 'packages/a/package.json'
      at Context.<anonymous> (test\workspaces.test.ts:252:26)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

  5) --workspace
       update more than one workspace:
     AssertionError: expected {} to have property 'packages/a/package.json'
      at Context.<anonymous> (test\workspaces.test.ts:267:26)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

  6) --workspace and --root
       update root project and single workspace:
     AssertionError: expected { 'package.json': { …(2) } } to have property 'packages/a/package.json'
      at Context.<anonymous> (test\workspaces.test.ts:337:26)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

  7) --workspace and --root
       update more than one workspace:
     AssertionError: expected { 'package.json': { …(2) } } to have property 'packages/a/package.json'
      at Context.<anonymous> (test\workspaces.test.ts:353:26)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by raineorshine** [comment]
Yes, this is a known problem, though I hadn't made a ticket for it so I am glad you said something. 

The GitHub workflow does include Windows. The CI has been failing for about three months now. Just waiting for a generous Windows user to investigate.

**Comment by grbd** [comment]
I was just about to do a pull request but all of a sudden the code got updated :)

The filtering of the workspaces when --workspace is used needs a replace statement adding to it to account for windows directory paths
```
      // add workspace packages
      pkgs = [
        ...pkgs,
        ...(options.workspaces
          ? // --workspaces
            workspacePackageFiles
          : // --workspace
            workspacePackageFiles.filter(pkgFile =>
              options.workspace?.some(workspace =>
                workspaces?.some(
                  workspacePattern =>
                    // use replace to convert Windows path to *nix path
                    pkgFile ===
                    path
                      .join(cwd, path.dirname(workspacePattern), workspace, defaultPackageFilename)
                      .replace(/\\/g, '/'),
                ),
              ),
            )),
      ]
    }
```

Just need to figure out where that filter was moved to

**Comment by raineorshine** [comment]
Oops! Was refactoring earlier today :). Thanks for your help!
