### ISSUE TITLE
ncu fails with "TypeError: dep.includes is not a function" for package.json with bundleDependencies

### ISSUE THREAD

**Issue by tsondergaard** [raineorshine/npm-check-updates#1256]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---

## Steps to Reproduce

Steps:

```
mkdir example
cd example
npm init --force
npm install --save --save-bundle tmp uuid
npm install --no-save npm-check-updates
npx ncu -u
```

## Current Behavior
ncu -u fails with the following output:
```
Upgrading /home/ts/src/example/package.json
[====================] 1/1 100%
TypeError: dep.includes is not a function
    at /home/ts/src/example/node_modules/npm-check-updates/build/src/lib/getPreferredWildcard.js:22:134
    at Array.find (<anonymous>)
    at /home/ts/src/example/node_modules/npm-check-updates/build/src/lib/getPreferredWildcard.js:22:104
    at arrayAggregator (/home/ts/src/example/node_modules/lodash/_arrayAggregator.js:17:32)
    at /home/ts/src/example/node_modules/lodash/_createAggregator.js:19:12
    at getPreferredWildcard (/home/ts/src/example/node_modules/npm-check-updates/build/src/lib/getPreferredWildcard.js:22:42)
    at upgradeDependencies (/home/ts/src/example/node_modules/npm-check-updates/build/src/lib/upgradeDependencies.js:49:57)
    at upgradePackageDefinitions (/home/ts/src/example/node_modules/npm-check-updates/build/src/lib/upgradePackageDefinitions.js:29:68)
    at async runLocal (/home/ts/src/example/node_modules/npm-check-updates/build/src/lib/runLocal.js:163:65)
    at async runUpgrades (/home/ts/src/example/node_modules/npm-check-updates/build/src/index.js:215:20)
```

## Expected Behavior
ncu -u completes without an error

Versions:
```
$ node --version
v18.1.0
$ npm --version
8.8.0
$ npx ncu --version
16.6.0
```

**Comment by raineorshine** [comment]
After a little research I've determined, amusingly, that the `bundleDependencies` logic is completely erroneous. I assumed `bundleDependencies` had the same format as the other dependencies sections when I added it back in d319202eab5ea875fa3a40eea9496da1df4c01f6. It's just an array of package names, so there is nothing there to upgrade! 🤦‍♀️

Removed and published to `v16.6.1` :).

**Comment by raineorshine** [comment]
@gklasen I wasn't aware of that dependency format. Could you link me to documentation? I don't see it in npm's docs: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#dependencies

**Comment by gklasen** [comment]
The project i was updating was couple of years old. I think you can ignore, as they (npm) seem to have removed this possibility.
