### ISSUE TITLE
ncu with pnpm does not honor workspace configuration file

### ISSUE THREAD

**Issue by nils-christian** [raineorshine/npm-check-updates#1285]
- [x ] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x ] I am using the latest version of `npm-check-updates`
- [x ] I am using `node >= 14.14`

---

## Steps to Reproduce

We have a multi module project each containing a _.npmrc_ file setting only _cafile_. In the root folder containing the _pnpm-workspace.yaml_, we have another _.npmrc_ file contaning the _registry_ entry. This is recognized correctly by _pnpm_, as the command _pnpm config list_ shows it.

However, once we use ncu, the correct registry is not used. Instead we have to pass the registry as additional parameter to ncu for this to work.

Steps:

Call _ncu_ in the module folder.

## Current Behavior

The wrong registry (the default registry) is used.

## Expected Behavior

The registry specified in the root _.npmrc_ file should be used.

**Comment by raineorshine** [comment]
Hi, thanks for reporting. 

Workspace mode is only supported in the project root, with `--workspaces` or `--workspace X`. If you run ncu in a workspace project, it will run as if it is a standalone module. It will not use any npm settings in the root.

Perhaps this should be considered a bug, although I'm a little nervous about automatically reading npm configs from higher up the tree. It introduces less explicit behavior and limits flexibility if a user does want to run ncu in a standalone way. Though if we detect that the current package is within a workspace it may make it a sensible default. 

In the mean time I can suggest two workarounds:

1. Always run ncu from the project root with `--workspace X`.
2. Copy the `registry` entry to the `.ncurc` in each workspace package.

It would be nice if the ncurc could inherit from the project root ncurc using `configFilePath`.

**Comment by nils-christian** [comment]
Hi @raineorshine,

I can understand your hestitation to read files from other directories, but it would be (in my opinion) the expected behaviour when working with pnpm. It is weird that _pnpm config list_ would show the registry correctly configured, _ncu_ would use _pnpm_ but would use another configuration (and thus with another registry) than _pnpm_.

About your question. As far as I can see npm works differently. 

From https://docs.npmjs.com/cli/v7/configuring-npm/npmrc:
- per-project config file (/path/to/my/project/.npmrc)
- per-user config file (~/.npmrc)
- global config file ($PREFIX/etc/npmrc)
- npm builtin config file (/path/to/npm/npmrc)

From https://pnpm.io/npmrc:
- per-project configuration file (/path/to/my/project/.npmrc)
- per-workspace configuration file (the directory that contains the pnpm-workspace.yaml file)
- per-user configuration file (~/.npmrc)
- global configuration file (/etc/npmrc)

So the per-workspace configuration is a _pnpm_ exclusive way. So I understand if you say that you do not want to support this behaviour. In this case it might be a good idea to document this somewhere at least.

**Comment by raineorshine** [comment]
Thanks for the additional info. 

It's not that I don't want to support it. It's just that non-standard, if you will, package manager features tend to get implemented later. We need people like you to report unexpected behavior on those systems! Ideally npm-check-updates works seamlessly and as expected with any supported package manager. 

Usually an alternative package manager enhances npm's functionality, but there have been cases where the alternative behavior was ambiguous and undesirable. Therefore, we make sure to think critically about the deviant behavior and ensure it is a good thing before following it in npm-check-updates. 

In this case, the behavior is clearly desirable. My plan is to walk up the file tree from the package file, identify any pnpm-workspace.yaml file, and load the npmrc file in that directory if it exists.

**Comment by raineorshine** [comment]
@nils-christian I added an initial implementation that reads the `.npmrc` file from the same folder as `pnpm-workspace.yaml`. Please try it out at your convenience! Published to `v16.8.2`.

**Comment by nils-christian** [comment]
Hi @raineorshine,

Thank you. I tested this with 16.10.0. To me it seems that something is not quite correct yet. We have two .npmrc-files. One in the folder where I call _ncu_ and one in the root folder. Both contain an entry for _cafile_ pointing to different locations. However, only the one from the root-directory is used, which is not correct.

- .npmrc
- certificate.pem
- subfolder
  - .npmrc
  - certificate.pem

The .npmrc file in the root directory points to "certificate.pem" whereas the file in the subfolder points to "../certificate.pem". Calling _ncu_ in _subfolder_ leads to a "no such file errror". So I would expect ncu to merge the settings in both .npmrc-files, giving the properties in the subfolder file preference.

**Comment by raineorshine** [comment]
Yes, it should override and merge. I'll look into it.

**Comment by nils-christian** [comment]
Hi @raineorshine,

Looks like it's still the same error with 16.10.1 (no such file). According to the verbose output, only the .npmrc in the root directory is used. I cannot see anything about a merge. Here is the output (I had to remove some parts though):

```
 $ ncu --verbose                                                                                                                                                
Using pnpm                                                                                                                                                     
Initializing                                                                                                                                                   
Running in local mode                                                                                                                                          
Finding package file data                                                                                                                                      
Checking C:\<REMOVED>\package.json                                                                   
                                                                                                                                                               
Options:                                                                                                                                                       
{                                                                                                                                                              
  args: [],                                                                                                                                                    
  cacheExpiration: 10,                                                                                                                                         
  cacheFile: '~/.ncu-cache.json',                                                                                                                              
  cacher: undefined,                                                                                                                                           
  cli: false,                                                                                                                                                 
  dep: [ 'prod', 'dev', 'optional' ],                                                                                                                          
  errorLevel: 1,                                                                                                                                               
  filter: undefined,                                                                                                                                           
  filterVersion: undefined,                                                                                                                                    
  format: [],                                                                                                                                                  
  json: false,                                                                                                                                                 
  loglevel: 'verbose',                                                                                                                                         
  minimal: false,                                                                                                                                              
  packageManager: 'pnpm',                                                                                                                                      
  prefix: undefined,                                                                                                                                           
  reject: undefined,                                                                                                                                           
  rejectVersion: undefined,                                                                                                                                    
  retry: 3,                                                                                                                                                    
  target: 'latest',                                                                                                                                            
  verbose: true,                                                                                                                                               
  workspace: []                                                                                                                                                
}                                                                                                                                                              
                                                                                                                                                               
Current versions:                                                                                                                                              
{                                                                                                                                                              
  '<REMOVED>': 'workspace:*',                                                                                                                      
  '<REMOVED>': '<REMOVED>',                                                                                                                            
  autonumeric: '4.6.0',                                                                                                                                        
  'bootstrap-vue': '2.23.1',                                                                                                                                   
  vue: '2.7.14',                                                                                                                                               
  '@babel/core': '7.21.3',                                                                                                                                     
  '@babel/eslint-parser': '7.21.3',                                                                                                                            
  '@babel/preset-env': '7.20.2',                                                                                                                               
  '@vue/component-compiler-utils': '3.3.0',                                                                                                                    
  axios: '1.3.4',                                                                                                                                              
  'css-loader': '6.7.3',                                                                                                                                       
  'esbuild-loader': '3.0.1',                                                                                                                                   
  eslint: '8.36.0',                                                                                                                                            
  'eslint-config-standard': '17.0.0',                                                                                                                          
  'eslint-friendly-formatter': '4.0.1',                                                                                                                        
  'eslint-import-resolver-alias': '1.1.2',                                                                                                                     
  'eslint-plugin-html': '7.1.0',                                                                                                                               
  'eslint-plugin-import': '2.27.5',                                                                                                                            
  'eslint-plugin-n': '15.6.1',                                                                                                                                 
  'eslint-plugin-node': '11.1.0',                                                                                                                              
  'eslint-plugin-promise': '6.1.1',                                                                                                                            
  'eslint-plugin-vue': '9.9.0',                                                                                                                                
  'html-webpack-plugin': '5.5.0',                                                                                                                              
  jquery: '3.6.4',                                                                                                                                             
  'node-sass': '8.0.0',                                                                                                                                        
  'sass-loader': '13.2.1',                                                                                                                                     
  'source-map-loader': '4.0.1',                                                                                                                                
  'vue-hot-reload-api': '2.3.4',                                                                                                                               
  'vue-loader': '15.10.1',                                                                                                                                     
  'vue-style-loader': '4.1.3',                                                                                                                                 
  'vue-template-compiler': '2.7.14',                                                                                                                           
  webpack: '5.76.3',                                                                                                                                           
  'webpack-cli': '5.0.1'                                                                                                                                       
}                                                                                                                                                              
                                                                                                                                                               
Using pnpm workspace config at <REMOVED>\.npmrc:                                                                                                  
Error: ENOENT: no such file or directory, open '<REMOVED>.pem'                                                                                                        
    at Object.openSync (node:fs:600:3)                                                                                                                         
    at Object.readFileSync (node:fs:468:35)                                                                                                                    
    at cafile (<REMOVED>\AppData\Roaming\nvm\v18.13.0\node_modules\npm-check-updates\build\src\package-managers\npm.js:60:41)              
    at <REMOVED>\AppData\Roaming\nvm\v18.13.0\node_modules\npm-check-updates\build\src\package-managers\npm.js:169:28                      
    at <REMOVED>\AppData\Roaming\nvm\v18.13.0\node_modules\npm-check-updates\build\src\lib\keyValueBy.js:14:15                             
    at Array.forEach (<anonymous>)                                                                                                                             
    at keyValueBy (<REMOVED>\AppData\Roaming\nvm\v18.13.0\node_modules\npm-check-updates\build\src\lib\keyValueBy.js:11:33)                
    at normalizeNpmConfig (<REMOVED>\AppData\Roaming\nvm\v18.13.0\node_modules\npm-check-updates\build\src\package-managers\npm.js:152:48) 
    at <REMOVED>\AppData\Roaming\nvm\v18.13.0\node_modules\npm-check-updates\build\src\package-managers\pnpm.js:30:49 {                    
  errno: -4058,                                                                                                                                                
  syscall: 'open',                                                                                                                                             
  code: 'ENOENT',                                                                                                                                              
  path: '<REMOVED>.pem'                                                                                                                                               
}                    
```

**Comment by nils-christian** [comment]
Hi @raineorshine,

That looks very good - thank you very much. I think 16.10.2 solves the issue.

**Comment by nils-christian** [comment]
Closed as fixed.
