### ISSUE TITLE
ncu does not use _authToken for private, scoped packages

### ISSUE THREAD

**Issue by regnaio** [raineorshine/npm-check-updates#1330]
`.npmrc` (for private GitLab package registry)
```
@<SCOPE>:registry=https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/packages/npm/
//gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/packages/npm/:_authToken=${GITLAB_API_PERSONAL_ACCESS_TOKEN}
```

```shell
ncu

Checking /<PATH>/package.json
[===============-----] 3/4 75%

 @<SCOPE>/<PACKAGE> 404 Not Found - GET https://gitlab.com/api/v4/projects/<GITLAB_PROJECT_ID>/packages/npm/@<SCOPE>%2f<PACKAGE> - Project not found. Either your internet connection is down or unstable and all 3 retry attempts failed, or the registry is not accessible, or the package does not exist.
```

The following commands succeed:
```shell
npm cache clean --force

npm i @<SCOPE>/<PACKAGE>@latest --registry=https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/packages/npm/
```

Moreover, if I enter `https://gitlab.com/api/v4/projects/<GITLAB_PROJECT_ID>/packages/npm/@<SCOPE>%2f<PACKAGE>` into my browser (logged into GitLab), it shows a good JSON with details about the package

So, it looks like `ncu -u` is not using `_authToken` in `.npmrc` and thus failing with a 404 when trying to find the package

---

I've read other related issues and PRs, but none of them resolve my issue:
- https://github.com/raineorshine/npm-check-updates/issues/519
- https://github.com/raineorshine/npm-check-updates/issues/556
- https://github.com/raineorshine/npm-check-updates/pull/557
- https://github.com/raineorshine/npm-check-updates/issues/1022

**Comment by raineorshine** [comment]
Hi, thanks for reporting. Can you provide some additional pieces of information?

- `node -v`
- `npm -v`
- `ncu --verbose` (with authTokens removed)
- `npx pacote packument @SCOPE/PACKAGE`

npm-check-updates reads, parses, and passes the npm config through to [pacote](https://github.com/npm/pacote/) which uses [npm-registry-fetch](https://github.com/npm/npm-registry-fetch) to request versions from the registry.

**Comment by raineorshine** [comment]
Thanks. I'll look into it. Just need to recreate the scenario. 

I had assumed pacote would pick up the registry, but I guess that's not the case. So we still don't know if the issue is in npm-check-updates or pacote.

**Comment by raineorshine** [comment]
Can you confirm that the error only occurs for scoped packages, and un-scoped packages on the same private registry work fine?

**Comment by raineorshine** [comment]
Thanks!

I'm not sure what I'm missing with the pacote call. If we could get that to work, it might clue us in to what is wrong with the npm-check-updates code.

**Comment by ZenwalkerD** [comment]
I am as well facing the same issue on Node 19, 21 as well especially for the scoped registry. 
I am able to get the packages installed via NPM from scoped registry; but NCU fails to run! 

I get the error as shown:

```
$ ncu
Checking D:\Projects\Src\Current-Working\APP-SoftwareManager\src\Cloud\package.json
[======--------------] 17/57 29%HttpErrorGeneral: 401 Unauthorized - GET https://private-repo/api/v4/packages/npm/@simpl%2felement-icons
    at D:\Tools\NVM\v19.9.0\node_modules\npm-check-updates\node_modules\npm-registry-fetch\lib\check-response.js:95:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RegistryFetcher.packument (D:\Tools\NVM\v19.9.0\node_modules\npm-check-updates\node_modules\pacote\lib\registry.js:87:19)
    at async viewMany (D:\Tools\NVM\v19.9.0\node_modules\npm-check-updates\build\src\package-managers\npm.js:400:18)
    at async viewOne (D:\Tools\NVM\v19.9.0\node_modules\npm-check-updates\build\src\package-managers\npm.js:448:20)
    at async distTag (D:\Tools\NVM\v19.9.0\node_modules\npm-check-updates\build\src\package-managers\npm.js:586:24)
    at async getPackageVersionProtected (D:\Tools\NVM\v19.9.0\node_modules\npm-check-updates\build\src\lib\queryVersions.js:70:29)
    at async D:\Tools\NVM\v19.9.0\node_modules\npm-check-updates\node_modules\p-map\index.js:57:22 {
  headers: [Object: null prototype] {
    server: [ 'nginx' ],
    date: [ 'Mon, 22 Jan 2024 10:31:09 GMT' ],
    'content-type': [ 'application/json' ],
    'content-length': [ '30' ],
    connection: [ 'keep-alive' ],
    'cache-control': [ 'no-cache' ],
    'content-security-policy': [ "default-src 'none'" ],
    vary: [ 'Origin' ],
    'x-content-type-options': [ 'nosniff' ],
    'x-frame-options': [ 'SAMEORIGIN' ],
    'x-gitlab-meta': [ '{"correlation_id":"01HMRBJN9VRTP91QJE7GG0V99M","version":"1"}' ],
    'x-request-id': [ '01HMRBJN9VRTP91QJE7GG0V99M' ],
    'x-runtime': [ '0.214866' ],
    'x-fetch-attempts': [ '1' ]
  },
  statusCode: 401,
  code: 'E401',
  method: 'GET',
  uri: 'https://private-repo/api/v4/packages/npm/@simpl%2felement-icons',
  body: { message: '401 Unauthorized' },
  pkgid: '@simpl/element-icons@*'
}
```

**Comment by raineorshine** [comment]
Thanks, @ZenwalkerD. Sorry you're running into this issue as well. 

The absolute best way to help out is to build npm-check-updates from source and do some live debugging. Unfortunately there is little I can do without being able to reproduce on my end, but I'm happy to point out the relevant code.

**Comment by bourquep** [comment]
I have a repro here: https://github.com/bourquep/ncu-external-registry

- Node version: `v20.9.0`
- NPM version: `10.1.0`
- `ncu --verbose`:

```
Initializing
Running in local mode
Finding package file data
Checking /Users/pascal/Dev/experiments/ncu-external-registry/package.json

Options:
{
  args: [],
  cacheExpiration: 10,
  cacheFile: '~/.ncu-cache.json',
  cli: true,
  concurrency: 8,
  deep: false,
  dep: [ 'prod', 'dev', 'optional', 'packageManager' ],
  deprecated: true,
  errorLevel: 1,
  format: [],
  install: 'prompt',
  json: false,
  loglevel: 'verbose',
  minimal: false,
  packageManager: 'npm',
  registryType: 'npm',
  retry: 3,
  root: true,
  target: 'latest',
  verbose: true,
  workspace: []
}

Current versions:
{
  '@buf/googleapis_googleapis.bufbuild_es': '2.0.0-20240827201746-e7f8d366f526.2'
}

npm config (user):
{
  '@buf:registry': 'https://buf.build/gen/npm/v1/',
  configNames: [ 'npmrc', '.npmrc' ],
  cwd: '/Users/pascal/Dev/experiments/ncu-external-registry',
  envPrefix: /^npm_config_/i,
  fullMetadata: false,
  globalconfig: '/Users/pascal/.nvm/versions/node/v20.9.0/etc/npmrc',
  savePrefix: '',
  userconfig: '/Users/pascal/.npmrc'
}

Latest versions:
{}

Upgraded versions:
{}


 @buf/googleapis_googleapis.bufbuild_es  404 Not Found - GET https://buf.build/gen/npm/v1/%40buf%2Fgoogleapis_googleapis.bufbuild_es. All 3 retry attempts failed. Either your internet connection is down, the registry is inaccessible, the authentication credentials are invalid, or the package does not exist. 
```

**Comment by regnaio** [comment]
I'm really sorry to share that this did not resolve my issue :(

cc @XhmikosR @raineorshine 

```shell
ncu --version
23.1.0

ncu
Checking /home/nonroot/app/packages/core/common/package.json
[====================] 13/13 100%

 @channel/common  HttpErrorGeneral: 401 Unauthorized - GET https://gitlab.com/api/v4/projects/<GITLAB_PROJECT_ID>/packages/npm/@channel%2Fcommon - 401 Unauthorized 
 @log/common          HttpErrorGeneral: 401 Unauthorized - GET https://gitlab.com/api/v4/projects/<GITLAB_PROJECT_ID>/packages/npm/@log%2Fcommon - 401 Unauthorized 
 @loop/common        HttpErrorGeneral: 401 Unauthorized - GET https://gitlab.com/api/v4/projects/<GITLAB_PROJECT_ID>/packages/npm/@loop%2Fcommon - 401 Unauthorized 
 @types/ammo          HttpErrorGeneral: 401 Unauthorized - GET https://gitlab.com/api/v4/projects/<GITLAB_PROJECT_ID>/packages/npm/@types%2Fammo - 401 Unauthorized 
 @types/babylon    HttpErrorGeneral: 401 Unauthorized - GET https://gitlab.com/api/v4/projects/<GITLAB_PROJECT_ID>/packages/npm/@types%2Fbabylon - 401 Unauthorized 
 @types/physx        HttpErrorGeneral: 401 Unauthorized - GET https://gitlab.com/api/v4/projects/<GITLAB_PROJECT_ID>/packages/npm/@types%2Fphysx - 401 Unauthorized 
 @types/recast      HttpErrorGeneral: 401 Unauthorized - GET https://gitlab.com/api/v4/projects/<GITLAB_PROJECT_ID>/packages/npm/@types%2Frecast - 401 Unauthorized
```

`.npmrc`
```
@channel:registry=https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/packages/npm/
@log:registry=https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/packages/npm/
@loop:registry=https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/packages/npm/
@types:registry=https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/packages/npm/
@core:registry=https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/packages/npm/
//gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/packages/npm/:_authToken=${GITLAB_API_PERSONAL_ACCESS_TOKEN}
```

**Comment by XhmikosR** [comment]
You need to share a minimal reproducible case. `GITLAB_PROJECT_ID` doesn't really help debugging this further. I need to be able to reproduce this 100% in order to be able to look at this. So, create a new issue with all the needed info.

**Comment by regnaio** [comment]
Thank you so much for your help, XhmikosR! Will do!

**Comment by XhmikosR** [comment]
@regnaio: That's an empty repro. Do you plan to add more stuff?

**Comment by XhmikosR** [comment]
Might be worth checking if this branch fixes your issue in the meantime: https://github.com/raineorshine/npm-check-updates/compare/main...xmr/fix-fetch-url. Otherwise, we still need a minimal reproducible case.

**Comment by regnaio** [comment]
@XhmikosR , my mistake, indeed it seems to be solved 😄

---

I was actually running into another issue: https://github.com/raineorshine/npm-check-updates/issues/2078

My `.npmrc` references environment variables like:

```conf
//gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/packages/npm/:_authToken=${GITLAB_API_PERSONAL_ACCESS_TOKEN}
```

`ncu` successfully picks up `GITLAB_API_PERSONAL_ACCESS_TOKEN` but fails to pick up `GITLAB_PROJECT_ID` (`npm` successfully picks up both, so I thought `ncu` would too)

Sorry for the delay! I've updated the repo with the reproduction: https://github.com/regnaio/ncu-repro

Thank you so much for all of your help, XhmikosR!!

**Comment by XhmikosR** [comment]
Where is it fixed then? On main (stable release) or my branch above?

The other issue is a separate one, I'll try to have a look later.

**Comment by regnaio** [comment]
Ooh sorry for the confusion, all works fine on `main` with regards to this #1330 issue!
