### ISSUE TITLE
bun.cmd id not recognized

### ISSUE THREAD

**Issue by HighError** [raineorshine/npm-check-updates#1400]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---

## Steps to Reproduce

Steps:

1. Run npm-check-updates
2. Accept to install updates via bun on Windows

## Current Behavior

```powershell
√ Run bun install to install new versions? ... yes
Installing dependencies...
'bun.cmd' is not recognized as an internal or external command,
operable program or batch file.

Error: spawn bun.cmd ENOENT
    at C:\Users\Admin\.bun\install\global\node_modules\npm-check-updates\build\src\index.js:178:23
```
## Expected Behavior

Command run without error

I think the problem is that `bun.cmd` is used, although Windows uses the `bun` (`bun i`) command for bun by default.
And since `bun.cmd` is not a registered command, an error occurs

**Comment by raineorshine** [comment]
Hi, thanks for reporting. It looks like Windows support was added to Bun recently, so we can try to turn on Bun support in npm-check-updates.

I changed it to use `bun` instead of `bun.cmd` and published to `v16.14.20-0`. Can you try `npx npm-check-updates@16.14.20-0 -u` and let me know if that works?

P.S. Out of curiosity, what do you get when you run `node -p process.platform`? I would have expected the latest npm-check-updates to throw an error "Bun not yet supported on Windows". It checks `process.platform` to determine the OS.

**Comment by raineorshine** [comment]
> Working good
> I run command `bunx npm-check-updates -i` (with npx too)

Great, I'll get that merged and published to `latest` then.

> node -p process.platform - `win32`

Huh. I can't explain why you were able to make it to the install step, but I guess it's not a problem now!

**Comment by raineorshine** [comment]
Published to `v16.14.20`.

**Comment by HighError** [comment]
I run with `bunx` and maybe this failure skips to the installation

![image](https://github.com/raineorshine/npm-check-updates/assets/46526245/bccfd666-4ba9-46d5-950c-25b74d82922a)

**Comment by raineorshine** [comment]
Yeah, that could explain it.

**Comment by HighError** [comment]
Again
Running by `npx npm-check-updates -i` and `bunx npm-check-updates -i`

```powershell
√ Run bun install to install new versions? ... yes
Installing dependencies...
'bun.cmd' is not recognized as an internal or external command,
operable program or batch file.

Error: spawn bun.cmd ENOENT
    at C:\Users\HighError\AppData\Local\npm-cache\_npx\0a80f0fb114540fe\node_modules\npm-check-updates\build\index.js:540:2145
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Unhandled Rejection! This is a bug and should be reported: https://github.com/raineorshine/npm-check-updates/issues
```

**Comment by OwenVey** [comment]
Issue still happens for me with 17.1.14.

`node -p process.platform` logs `win32`.

The fix above from @davidmannion did work for me for what it's worth.

**Comment by raineorshine** [comment]
Is there a way to detect the correct bun executable command for a given Windows shell? I think that’s what is needed to have a proper solution.

**Comment by phenomen** [comment]
Just change the command to `bun` instead of `bun.cmd`

**Comment by raineorshine** [comment]
I think I found the culprit. There's a bit of abstraction when determining the package manager executable, and `.cmd` was added in another place. 

Please try out `v17.1.16` and let me know if that works.

**Comment by phenomen** [comment]
@raineorshine can confirm it works now. Thanks!
