### ISSUE TITLE
Format ownerChanged fails with type error when using bun: "packageManager.packageAuthorChanged is not a function"

### ISSUE THREAD

**Issue by callumlocke** [raineorshine/npm-check-updates#1435]
- [/] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)

---

## Steps to Reproduce

.ncurc: none

Dependencies: N/A

Steps:
1. In a project with a `bun.lockb`, run `bunx ncu --interactive --format ownerChanged`

## Current Behavior

- Fails with a `TypeError`

## Expected Behavior

- It should show the interactive update dialog.

## Notes

- `bunx ncu --help format` shows available formats: `group`, `ownerChanged`, `time` and `lines`. They all work with bun except `ownerChanged`.

<details>
<summary>Full termimal output</summary>

```sh
> bunx ncu --interactive --format ownerChanged
Upgrading /Users/callum/issue-demo/package.json
[====================] 61/61 100%
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
TypeError: packageManager.packageAuthorChanged is not a function
    at /Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:44:51
    at Array.reduce (<anonymous>)
    at getOwnerPerDependency (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:41:41)
    at runLocal (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/lib/runLocal.js:176:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUpgrades (/Users/callum/issue-demo/node_modules/npm-check-updates/build/src/index.js:240:20)
```

</details>

**Comment by raineorshine** [comment]
I added interim support by having it use npm internally to fetch `ownerChanged`. This will fail if npm is not installed on your system. 

Proper support depends on https://github.com/oven-sh/bun/issues/1224.

Published in `v17.0.0`

**Comment by XhmikosR** [comment]
I wonder if this fixed nowadays? If so, maybe the workaround could/should be dropped?

**Comment by raineorshine** [comment]
Native support of `bun view` should now make this possible. The npm fallback can be dropped, although depending on bun's output format it may need to be munged to fall nicely into ncu.

**Comment by XhmikosR** [comment]
The original crash is fixed since v17.0.0, so the issue as reported is resolved.

Re dropping the npm fallback: I pushed a partial native migration on [`xmr/bun-info`](https://github.com/raineorshine/npm-check-updates/compare/xmr/bun-info). `packageAuthorChanged`, `getPeerDependencies`, and `getEngines` now use `bun info`. `getPeerDependencies` was the only real bug, it spawned the npm CLI and failed without npm installed.

I left the version resolvers (`latest`, `greatest`, etc.) on `npm-registry-fetch` since they need a full packument that `bun info` doesn't return. Full `bunfig.toml` support touches all of those and belongs in a bigger refactor, so I'm not sure the rest is worth it here.

**Comment by XhmikosR** [comment]
@raineorshine feel free to pick my branch above if you think is worth it, or let me know to open a PR.

**Comment by raineorshine** [comment]
Looks great. I would to have that in a PR.
