### ISSUE TITLE
Unable to use pnpm

### ISSUE THREAD

**Issue by codybooher** [raineorshine/npm-check-updates#1444]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)

---

## Steps to Reproduce

.ncurc:

```js

```

Dependencies:

```json

```

Steps:

I am using pnpm, and have used it in the past without issue. When I run the command `ncu -i -p pnpm --format group`, I get an error.

## Current Behavior

run: `ncu -i -p pnpm --format group`

```
Error: Invalid package manager: pnpm
    at getPresetPackageManager (/usr/local/lib/node_modules/npm-check-updates/build/src/lib/getPackageManager.js:19:19)
    at getPackageManager (/usr/local/lib/node_modules/npm-check-updates/build/src/lib/getPackageManager.js:28:19)
    at queryVersions (/usr/local/lib/node_modules/npm-check-updates/build/src/lib/queryVersions.js:27:66)
    at async upgradePackageDefinitions (/usr/local/lib/node_modules/npm-check-updates/build/src/lib/upgradePackageDefinitions.js:23:34)
    at async runLocal (/usr/local/lib/node_modules/npm-check-updates/build/src/lib/runLocal.js:165:65)
    at async runUpgrades (/usr/local/lib/node_modules/npm-check-updates/build/src/index.js:304:24)
```

## Expected Behavior

Should list out the dependencies in formatter group, like this:

![image](https://github.com/user-attachments/assets/816dc38d-a9ee-42e7-b2cb-d39eefe7b7b7)

**Comment by codybooher** [comment]
Restarted my computer 🤦
