### ISSUE TITLE
v17 request error for private package with proxy enabled

### ISSUE THREAD

**Issue by shaunxu** [raineorshine/npm-check-updates#1456]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)

May similar with https://github.com/raineorshine/npm-check-updates/issues/1436

---

## Steps to Reproduce

Private packages defined in `package.json`, use proxy, ether though environment variant `HTTPS_PROXY=http://HOST:PORT`, or through `.npmrc`, will cause `ncu` response `400 Bad Request`.

For example `HTTPS_PROXY=http://HOST:PORT npx ncu`

## Current Behavior

```
[================----] 4/5 80%vL: 400 Bad request - GET https://npm.pkg.github.com/@atinc/chaos
    at /Users/shaunxu/github/parthenon/node_modules/npm-check-updates/build/index.js:347:925
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  headers: [Object: null prototype] {
    'content-length': [ '90' ],
    'cache-control': [ 'no-cache' ],
    connection: [ 'close' ],
    'content-type': [ 'text/html' ],
    'x-fetch-attempts': [ '1' ]
  },
  statusCode: 400,
  code: 'E400',
  method: 'GET',
  uri: 'https://npm.pkg.github.com/@atinc/chaos',
  body: <Buffer 3c 68 74 6d 6c 3e 3c 62 6f 64 79 3e 3c 68 31 3e 34 30 30 20 42 61 64 20 72 65 71 75 65 73 74 3c 2f 68 31 3e 0a 59 6f 75 72 20 62 72 6f 77 73 65 72 20 ... 40 more bytes>,
  pkgid: '@atinc/chaos'
}
```

## Expected Behavior

Successful check.

**Comment by raineorshine** [comment]
Thanks for reporting. Given the specifics of npm config and authentication particular to each case, the best way to assist on this issue is to investigate it on the machine where it originates. It's difficult for me to reproduce the specific credentials on my machine. I'm happy to answer any questions you might have about the codebase.

**Comment by shaunxu** [comment]
Thanks @raineorshine I will try to provide more details for future investigation.

**Comment by LeahPike** [comment]
```
C:\GitHub\activ-master\src\applications git:[master]
ncu
Checking C:\GitHub\activ-master\src\applications\package.json
[====================] 53/54 98%ek: 403 Forbidden - GET https://npm.mobiscroll.com/%40mobiscroll%2Fangular-ivy - unregistered users are not allowed to access package @mobiscroll/angular-ivy
    at C:\Users\username\AppData\Roaming\npm\node_modules\npm-check-updates\build\index.js:347:974
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  headers: [Object: null prototype] {
    server: [ 'nginx' ],
    date: [ 'Mon, 07 Apr 2025 12:26:36 GMT' ],
    'content-type': [ 'application/json; charset=utf-8' ],
    'content-length': [ '94' ],
    connection: [ 'keep-alive' ],
    'x-powered-by': [ 'verdaccio/3.11.6' ],
    'access-control-allow-origin': [ '*' ],
    etag: [ 'W/"5e-g3e598w6sl/x6kTX5cTcIFGbrcA"' ],
    vary: [ 'Accept-Encoding' ],
    'x-status-cat': [ 'http://flic.kr/p/aV6jFK' ],
    'x-fetch-attempts': [ '1' ]
  },
  statusCode: 403,
  code: 'E403',
  method: 'GET',
  uri: 'https://npm.mobiscroll.com/%40mobiscroll%2Fangular-ivy',
  body: {
    error: 'unregistered users are not allowed to access package @mobiscroll/angular-ivy'
  },
  pkgid: '@mobiscroll/angular-ivy'
}
Unhandled Rejection! This is a bug and should be reported: https://github.com/raineorshine/npm-check-updates/issues
```

Still struggling with this.

**Comment by blwinters** [comment]
I'm running into a very similar error, also related to mobiscroll. [Mobiscroll](http://help.mobiscroll.com/en/articles/1195431-installing-mobiscroll-with-npm) and [Planby](https://docs-pro.planby.app/docs/intro/#option-1-install-planby-pro) both recommend putting credentials in the `.npmrc` file, which we have done for our project and that works fine when running `npm install`. So seems that `npm-check-updates` should also look at `.npmrc` to get the auth token and correct package registry for each of the packages listed in there. Here is a sanitized example of our `.npmrc`:

```
## Mobiscroll: http://help.mobiscroll.com/en/articles/1195431-installing-mobiscroll-with-npm
@mobiscroll:registry=https://npm.mobiscroll.com
//npm.mobiscroll.com/:_authToken=some_token_1

## Planby: https://docs-pro.planby.app/docs/intro/#option-1-install-planby-pro
@nessprim:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken=some_token_2

```

**Comment by raineorshine** [comment]
Hi @DelliriumX. This issue is specifically for `400 Bad Request`. If you are getting a different error, please create a new issue.

> This worked perfectly fine earlier, say, idk a month or two ago? (which is my main concern here, something changed)

That's great information. If that's the case, you can try older versions of `npm-check-updates` until you find where the regression was introduced. That will help narrow down the cause.

**Comment by XhmikosR** [comment]
Could someone try the code from main to see if the issue is still present? If not, try this branch too: https://github.com/raineorshine/npm-check-updates/compare/main...xmr/fix-fetch-url

Would be nice if we had a test can we could use to replicate the issue.

EDIT: or try v23.0.0, which has some related 404 fixes.

**Comment by XhmikosR** [comment]
So, is anyone able to confirm that v23 works? If not please give #1951 a go.

**Comment by raineorshine** [comment]
All quiet on the western front...
