### ISSUE TITLE
`ncu -i`: `Unable to resolve reference $eslint`

### ISSUE THREAD

**Issue by rakleed** [raineorshine/npm-check-updates#1477]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)

---

## Steps to Reproduce

Dependencies:

```json
  "dependencies": {
    "@ant-design/icons": "^5.5.1",
    "@emotion/is-prop-valid": "^1.3.1",
    "antd": "5.22.1",
    "chart.js": "^4.4.6",
    "dayjs": "^1.11.13",
    "downloadjs": "^1.4.7",
    "html2canvas": "^1.4.1",
    "jspdf": "^2.5.2",
    "mobx": "^6.13.5",
    "mobx-react-lite": "^4.0.7",
    "react": "^18.3.1",
    "react-chartjs-2": "^5.2.0",
    "react-datasheet": "^1.4.12",
    "react-dom": "^18.3.1",
    "react-router-dom": "^6.28.0",
    "react-transition-group": "^4.4.5",
    "styled-components": "^6.1.13",
    "uuid": "^11.0.3"
  },
  "devDependencies": {
    "@awmottaz/prettier-plugin-void-html": "^1.6.1",
    "@eslint-community/eslint-plugin-eslint-comments": "^4.4.1",
    "@eslint-react/eslint-plugin": "^1.16.1",
    "@eslint/config-inspector": "^0.5.6",
    "@eslint/js": "^9.15.0",
    "@ianvs/prettier-plugin-sort-imports": "^4.4.0",
    "@stylistic/eslint-plugin": "^2.11.0",
    "@stylistic/stylelint-plugin": "^3.1.1",
    "@swc/core": "^1.9.2",
    "@swc/plugin-styled-components": "^5.0.0",
    "@typescript-eslint/parser": "^8.15.0",
    "@vitejs/plugin-react-swc": "^3.7.1",
    "eslint": "^9.15.0",
    "eslint-config-flat-gitignore": "^0.3.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-import-resolver-alias": "^1.1.2",
    "eslint-import-resolver-oxc": "^0.4.0",
    "eslint-import-resolver-typescript": "^3.6.3",
    "eslint-interactive": "^11.1.0",
    "eslint-plugin-check-file": "^2.8.0",
    "eslint-plugin-depend": "^0.12.0",
    "eslint-plugin-diff": "^2.0.3",
    "eslint-plugin-import-x": "^4.4.2",
    "eslint-plugin-jsx-a11y": "^6.10.2",
    "eslint-plugin-mobx": "^0.0.13",
    "eslint-plugin-no-barrel-files": "^1.2.0",
    "eslint-plugin-no-comments": "^1.1.10",
    "eslint-plugin-no-unsanitized": "^4.1.2",
    "eslint-plugin-package-json": "^0.15.6",
    "eslint-plugin-perfectionist": "^4.0.2",
    "eslint-plugin-project-structure": "^3.10.3",
    "eslint-plugin-promise": "^7.1.0",
    "eslint-plugin-react-compiler": "^19.0.0-beta-a7bf2bd-20241110",
    "eslint-plugin-react-form-fields": "^1.2.22",
    "eslint-plugin-react-hooks": "^5.0.0",
    "eslint-plugin-react-perf": "^3.3.3",
    "eslint-plugin-react-refresh": "^0.4.14",
    "eslint-plugin-regexp": "^2.7.0",
    "eslint-plugin-simple-import-sort": "^12.1.1",
    "eslint-plugin-sonarjs": "^2.0.4",
    "eslint-plugin-sort-destructure-keys": "^2.0.0",
    "eslint-plugin-styled-components-a11y": "^2.1.36",
    "eslint-plugin-unicorn": "^56.0.1",
    "eslint-plugin-validate-jsx-nesting": "^0.1.1",
    "eslint-plugin-write-good-comments": "^0.2.0",
    "globals": "^15.12.0",
    "husky": "^9.1.7",
    "jsdoc": "^4.0.4",
    "knip": "^5.37.1",
    "lint-staged": "^15.2.10",
    "postcss-styled-syntax": "^0.7.0",
    "prettier": "^3.3.3",
    "prettier-plugin-jsdoc": "^1.3.0",
    "prettier-plugin-packagejson": "^2.5.3",
    "stylelint": "^16.10.0",
    "stylelint-config-idiomatic-order": "^10.0.0",
    "stylelint-config-standard": "^36.0.1",
    "stylelint-declaration-block-no-ignored-properties": "^2.8.0",
    "stylelint-high-performance-animation": "^1.10.0",
    "stylelint-order": "^6.0.4",
    "stylelint-plugin-defensive-css": "^1.0.4",
    "typescript": "^5.6.3",
    "typescript-eslint": "^8.15.0",
    "vite": "^5.4.11"
  },
  "overrides": {
    "eslint": "$eslint",
    "@typescript-eslint/parser": "$@typescript-eslint/parser"
  },
  "type": "module",
  "engines": {
    "node": ">=22.11.0"
  }
```

Steps:

1. 
```
ncu -i --format repo
```
2. Press Enter to update `@eslint-react/eslint-plugin` ^1.16.1 → ^1.16.2 and `eslint-plugin-perfectionist` ^4.0.2 → ^4.0.3
3. And press Enter again

## Current Behavior

In `package.json` the dependencies are updated but cannot be installed.

```log
npm error Unable to resolve reference $eslint
```

[2024-11-20T09_03_53_125Z-debug-0.log](https://github.com/user-attachments/files/17828485/2024-11-20T09_03_53_125Z-debug-0.log)

<details><summary>2024-11-20T09_03_53_125Z-debug-0.log</summary>

```log
0 verbose cli /opt/homebrew/Cellar/node@22/22.11.0/bin/node /opt/homebrew/opt/node@22/bin/npm
1 info using npm@10.9.0
2 info using node@v22.11.0
3 silly config load:file:/opt/homebrew/Cellar/node@22/22.11.0/lib/node_modules/npm/npmrc
4 silly config load:file:/Users/rakleed/Developer/react-crm-app/.npmrc
5 silly config load:file:/Users/rakleed/.npmrc
6 silly config load:file:/opt/homebrew/etc/npmrc
7 verbose title npm install
8 verbose argv "install"
9 verbose logfile logs-max:10 dir:/Users/rakleed/.npm/_logs/2024-11-20T09_03_53_125Z-
10 verbose logfile /Users/rakleed/.npm/_logs/2024-11-20T09_03_53_125Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
13 silly logfile done cleaning log files
14 silly idealTree buildDeps
15 silly fetch manifest @eslint-react/eslint-plugin@^1.16.2
16 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2feslint-plugin cache-miss
17 http fetch GET 200 https://registry.npmjs.org/@eslint-react%2feslint-plugin 20ms (cache hit)
18 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2feslint-plugin set size:2406932 disposed:false
19 silly fetch manifest eslint@^9.15.0
20 silly packumentCache full:https://registry.npmjs.org/eslint cache-miss
21 http fetch GET 200 https://registry.npmjs.org/eslint 86ms (cache hit)
22 silly packumentCache full:https://registry.npmjs.org/eslint set size:1680060 disposed:false
23 silly fetch manifest jiti@*
24 silly packumentCache full:https://registry.npmjs.org/jiti cache-miss
25 http fetch GET 200 https://registry.npmjs.org/jiti 2ms (cache hit)
26 silly packumentCache full:https://registry.npmjs.org/jiti set size:351297 disposed:false
27 silly fetch manifest typescript@^5.6.3
28 silly packumentCache full:https://registry.npmjs.org/typescript cache-miss
29 http fetch GET 200 https://registry.npmjs.org/typescript 10ms (cache hit)
30 silly packumentCache full:https://registry.npmjs.org/typescript set size:13482982 disposed:false
31 silly fetch manifest eslint-plugin-perfectionist@^4.0.3
32 silly packumentCache full:https://registry.npmjs.org/eslint-plugin-perfectionist cache-miss
33 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-perfectionist 7ms (cache hit)
34 silly packumentCache full:https://registry.npmjs.org/eslint-plugin-perfectionist set size:151270 disposed:false
35 silly placeDep ROOT @eslint-react/eslint-plugin@1.16.2 REPLACE for: i-tech-crm@1.0.0 want: ^1.16.2
36 silly placeDep ROOT eslint-plugin-perfectionist@4.0.3 REPLACE for: i-tech-crm@1.0.0 want: ^4.0.3
37 silly fetch manifest @typescript-eslint/scope-manager@^8.15.0
38 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2fscope-manager cache-miss
39 silly fetch manifest @typescript-eslint/type-utils@^8.15.0
40 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2ftype-utils cache-miss
41 silly fetch manifest @typescript-eslint/types@^8.15.0
42 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2ftypes cache-miss
43 silly fetch manifest @typescript-eslint/utils@^8.15.0
44 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2futils cache-miss
45 silly fetch manifest @eslint-react/shared@1.16.2
46 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fshared cache-miss
47 silly fetch manifest @eslint-react/tools@1.16.2
48 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2ftools cache-miss
49 silly fetch manifest @eslint-react/types@1.16.2
50 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2ftypes cache-miss
51 silly fetch manifest eslint-plugin-react-debug@1.16.2
52 silly packumentCache full:https://registry.npmjs.org/eslint-plugin-react-debug cache-miss
53 silly fetch manifest eslint-plugin-react-dom@1.16.2
54 silly packumentCache full:https://registry.npmjs.org/eslint-plugin-react-dom cache-miss
55 silly fetch manifest eslint-plugin-react-hooks-extra@1.16.2
56 silly packumentCache full:https://registry.npmjs.org/eslint-plugin-react-hooks-extra cache-miss
57 silly fetch manifest eslint-plugin-react-naming-convention@1.16.2
58 silly packumentCache full:https://registry.npmjs.org/eslint-plugin-react-naming-convention cache-miss
59 http fetch GET 200 https://registry.npmjs.org/@eslint-react%2ftypes 9ms (cache hit)
60 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2ftypes set size:1546735 disposed:false
61 silly fetch manifest eslint-plugin-react-web-api@1.16.2
62 silly packumentCache full:https://registry.npmjs.org/eslint-plugin-react-web-api cache-miss
63 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-react-debug 14ms (cache hit)
64 silly packumentCache full:https://registry.npmjs.org/eslint-plugin-react-debug set size:1811477 disposed:false
65 silly fetch manifest eslint-plugin-react-x@1.16.2
66 silly packumentCache full:https://registry.npmjs.org/eslint-plugin-react-x cache-miss
67 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2ftype-utils 24ms (cache hit)
68 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2ftype-utils set size:7196067 disposed:false
69 http fetch GET 200 https://registry.npmjs.org/@eslint-react%2fshared 38ms (cache hit)
70 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fshared set size:1585648 disposed:false
71 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2ftypes 49ms (cache hit)
72 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2ftypes set size:10123019 disposed:false
73 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2futils 73ms (cache hit)
74 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2futils set size:7745106 disposed:false
75 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2fscope-manager 100ms (cache hit)
76 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2fscope-manager set size:10321781 disposed:false
77 http fetch GET 200 https://registry.npmjs.org/@eslint-react%2ftools 131ms (cache hit)
78 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2ftools set size:1476205 disposed:false
79 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-react-naming-convention 135ms (cache hit)
80 silly packumentCache full:https://registry.npmjs.org/eslint-plugin-react-naming-convention set size:1888335 disposed:false
81 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-react-hooks-extra 141ms (cache hit)
82 silly packumentCache full:https://registry.npmjs.org/eslint-plugin-react-hooks-extra set size:1870483 disposed:false
83 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-react-dom 147ms (cache hit)
84 silly packumentCache full:https://registry.npmjs.org/eslint-plugin-react-dom set size:1805086 disposed:false
85 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-react-web-api 142ms (cache hit)
86 silly packumentCache full:https://registry.npmjs.org/eslint-plugin-react-web-api set size:533828 disposed:false
87 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-react-x 138ms (cache hit)
88 silly packumentCache full:https://registry.npmjs.org/eslint-plugin-react-x set size:1311186 disposed:false
89 silly fetch manifest typescript@^4.9.5 || ^5.3.3
90 silly packumentCache full:https://registry.npmjs.org/typescript cache-miss
91 http fetch GET 200 https://registry.npmjs.org/typescript 11ms (cache hit)
92 silly packumentCache full:https://registry.npmjs.org/typescript set size:13482982 disposed:false
93 silly placeDep ROOT @eslint-react/shared@1.16.2 OK for: @eslint-react/eslint-plugin@1.16.2 want: 1.16.2
94 silly placeDep ROOT @eslint-react/tools@1.16.2 OK for: @eslint-react/eslint-plugin@1.16.2 want: 1.16.2
95 silly placeDep ROOT @eslint-react/types@1.16.2 OK for: @eslint-react/eslint-plugin@1.16.2 want: 1.16.2
96 silly placeDep node_modules/@eslint-react/eslint-plugin @typescript-eslint/scope-manager@8.15.0 OK for: @eslint-react/eslint-plugin@1.16.2 want: ^8.15.0
97 silly placeDep node_modules/@eslint-react/eslint-plugin @typescript-eslint/type-utils@8.15.0 OK for: @eslint-react/eslint-plugin@1.16.2 want: ^8.15.0
98 silly placeDep node_modules/@eslint-react/eslint-plugin @typescript-eslint/types@8.15.0 OK for: @eslint-react/eslint-plugin@1.16.2 want: ^8.15.0
99 silly placeDep ROOT @typescript-eslint/utils@8.15.0 REPLACE for: @eslint-react/eslint-plugin@1.16.2 want: ^8.15.0
100 silly placeDep ROOT eslint-plugin-react-debug@1.16.2 OK for: @eslint-react/eslint-plugin@1.16.2 want: 1.16.2
101 silly placeDep ROOT eslint-plugin-react-dom@1.16.2 OK for: @eslint-react/eslint-plugin@1.16.2 want: 1.16.2
102 silly placeDep ROOT eslint-plugin-react-hooks-extra@1.16.2 OK for: @eslint-react/eslint-plugin@1.16.2 want: 1.16.2
103 silly placeDep ROOT eslint-plugin-react-naming-convention@1.16.2 OK for: @eslint-react/eslint-plugin@1.16.2 want: 1.16.2
104 silly placeDep ROOT eslint-plugin-react-web-api@1.16.2 OK for: @eslint-react/eslint-plugin@1.16.2 want: 1.16.2
105 silly placeDep ROOT eslint-plugin-react-x@1.16.2 OK for: @eslint-react/eslint-plugin@1.16.2 want: 1.16.2
106 silly fetch manifest picomatch@^4.0.2
107 silly packumentCache full:https://registry.npmjs.org/picomatch cache-miss
108 silly fetch manifest @typescript-eslint/types@8.15.0
109 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2ftypes cache-miss
110 silly fetch manifest @typescript-eslint/visitor-keys@8.15.0
111 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2fvisitor-keys cache-miss
112 silly fetch manifest @typescript-eslint/utils@8.15.0
113 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2futils cache-miss
114 silly fetch manifest @typescript-eslint/typescript-estree@8.15.0
115 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2ftypescript-estree cache-miss
116 silly fetch manifest @typescript-eslint/types@8.15.0
117 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2ftypes cache-miss
118 silly fetch manifest @typescript-eslint/scope-manager@8.15.0
119 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2fscope-manager cache-miss
120 silly fetch manifest @typescript-eslint/typescript-estree@8.15.0
121 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2ftypescript-estree cache-miss
122 silly fetch manifest string-ts@^2.2.0
123 silly packumentCache full:https://registry.npmjs.org/string-ts cache-miss
124 silly fetch manifest ts-pattern@^5.5.0
125 silly packumentCache full:https://registry.npmjs.org/ts-pattern cache-miss
126 silly fetch manifest @eslint-react/ast@1.16.2
127 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fast cache-miss
128 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2futils 12ms (cache hit)
129 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2futils set size:7745106 disposed:false
130 silly fetch manifest @eslint-react/core@1.16.2
131 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fcore cache-miss
132 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2ftypes 37ms (cache hit)
133 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2ftypes set size:10123019 disposed:false
134 silly fetch manifest @eslint-react/jsx@1.16.2
135 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fjsx cache-miss
136 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2ftypes 80ms (cache hit)
137 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2ftypes set size:10123019 disposed:false
138 silly fetch manifest @eslint-react/var@1.16.2
139 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fvar cache-miss
140 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2fscope-manager 108ms (cache hit)
141 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2fscope-manager set size:10321781 disposed:false
142 silly fetch manifest ts-pattern@^5.5.0
143 silly packumentCache full:https://registry.npmjs.org/ts-pattern cache-miss
144 http fetch GET 200 https://registry.npmjs.org/picomatch 130ms (cache hit)
145 silly packumentCache full:https://registry.npmjs.org/picomatch set size:116191 disposed:false
146 silly fetch manifest @eslint-react/ast@1.16.2
147 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fast cache-miss
148 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2fvisitor-keys 137ms (cache hit)
149 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2fvisitor-keys set size:9859318 disposed:false
150 silly fetch manifest @eslint-react/jsx@1.16.2
151 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fjsx cache-miss
152 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2ftypescript-estree 171ms (cache hit)
153 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2ftypescript-estree set size:14045304 disposed:false
154 silly fetch manifest @eslint-react/core@1.16.2
155 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fcore cache-miss
156 http fetch GET 200 https://registry.npmjs.org/string-ts 214ms (cache hit)
157 silly packumentCache full:https://registry.npmjs.org/string-ts set size:71408 disposed:false
158 silly fetch manifest @eslint-react/var@1.16.2
159 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fvar cache-miss
160 http fetch GET 200 https://registry.npmjs.org/@eslint-react%2fast 216ms (cache hit)
161 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fast set size:1650867 disposed:false
162 silly fetch manifest ts-pattern@^5.5.0
163 silly packumentCache full:https://registry.npmjs.org/ts-pattern cache-miss
164 http fetch GET 200 https://registry.npmjs.org/ts-pattern 221ms (cache hit)
165 silly packumentCache full:https://registry.npmjs.org/ts-pattern set size:471160 disposed:false
166 silly fetch manifest @eslint-react/jsx@1.16.2
167 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fjsx cache-miss
168 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2ftypescript-estree 231ms (cache hit)
169 silly packumentCache full:https://registry.npmjs.org/@typescript-eslint%2ftypescript-estree set size:14045304 disposed:false
170 silly fetch manifest @eslint-react/core@1.16.2
171 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fcore cache-miss
172 http fetch GET 200 https://registry.npmjs.org/ts-pattern 140ms (cache hit)
173 silly packumentCache full:https://registry.npmjs.org/ts-pattern set size:471160 disposed:false
174 silly packumentCache full:https://registry.npmjs.org/ts-pattern dispose
175 silly fetch manifest @eslint-react/var@1.16.2
176 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fvar cache-miss
177 http fetch GET 200 https://registry.npmjs.org/@eslint-react%2fast 142ms (cache hit)
178 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fast set size:1650867 disposed:false
179 silly fetch manifest @eslint-react/core@1.16.2
180 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fcore cache-miss
181 http fetch GET 200 https://registry.npmjs.org/@eslint-react%2fvar 179ms (cache hit)
182 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fvar set size:1514352 disposed:false
183 silly fetch manifest @eslint-react/jsx@1.16.2
184 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fjsx cache-miss
185 http fetch GET 200 https://registry.npmjs.org/ts-pattern 60ms (cache hit)
186 silly packumentCache full:https://registry.npmjs.org/ts-pattern set size:471160 disposed:true
187 silly packumentCache full:https://registry.npmjs.org/ts-pattern dispose
188 silly fetch manifest birecord@^0.1.1
189 silly packumentCache full:https://registry.npmjs.org/birecord cache-miss
190 http fetch GET 200 https://registry.npmjs.org/@eslint-react%2fjsx 212ms (cache hit)
191 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fjsx set size:1852169 disposed:false
192 silly fetch manifest @eslint-react/core@1.16.2
193 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fcore cache-miss
194 http fetch GET 200 https://registry.npmjs.org/@eslint-react%2fjsx 130ms (cache hit)
195 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fjsx set size:1852169 disposed:false
196 silly fetch manifest is-immutable-type@5.0.0
197 silly packumentCache full:https://registry.npmjs.org/is-immutable-type cache-miss
198 http fetch GET 200 https://registry.npmjs.org/@eslint-react%2fcore 83ms (cache hit)
199 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fcore set size:1793227 disposed:false
200 http fetch GET 200 https://registry.npmjs.org/@eslint-react%2fcore 275ms (cache hit)
201 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fcore set size:1793227 disposed:false
202 http fetch GET 200 https://registry.npmjs.org/@eslint-react%2fvar 94ms (cache hit)
203 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fvar set size:1514352 disposed:false
204 http fetch GET 200 https://registry.npmjs.org/@eslint-react%2fcore 49ms (cache hit)
205 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fcore set size:1793227 disposed:false
206 http fetch GET 200 https://registry.npmjs.org/@eslint-react%2fjsx 96ms (cache hit)
207 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fjsx set size:1852169 disposed:false
208 http fetch GET 200 https://registry.npmjs.org/birecord 44ms (cache hit)
209 silly packumentCache full:https://registry.npmjs.org/birecord set size:4442 disposed:false
210 http fetch GET 200 https://registry.npmjs.org/@eslint-react%2fcore 52ms (cache hit)
211 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fcore set size:1793227 disposed:false
212 http fetch GET 200 https://registry.npmjs.org/is-immutable-type 36ms (cache hit)
213 silly packumentCache full:https://registry.npmjs.org/is-immutable-type set size:177610 disposed:false
214 http fetch GET 200 https://registry.npmjs.org/@eslint-react%2fvar 63ms (cache hit)
215 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fvar set size:1514352 disposed:false
216 http fetch GET 200 https://registry.npmjs.org/@eslint-react%2fcore 52ms (cache hit)
217 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fcore set size:1793227 disposed:false
218 http fetch GET 200 https://registry.npmjs.org/@eslint-react%2fjsx 64ms (cache hit)
219 silly packumentCache full:https://registry.npmjs.org/@eslint-react%2fjsx set size:1852169 disposed:false
220 silly placeDep node_modules/@eslint-react/shared picomatch@4.0.2 OK for: @eslint-react/shared@1.16.2 want: ^4.0.2
221 silly placeDep ROOT @typescript-eslint/types@8.15.0 OK for: @eslint-react/types@1.16.2 want: ^8.15.0
222 silly placeDep ROOT @typescript-eslint/scope-manager@8.15.0 OK for: @typescript-eslint/utils@8.15.0 want: 8.15.0
223 silly placeDep ROOT @typescript-eslint/typescript-estree@8.15.0 OK for: @typescript-eslint/utils@8.15.0 want: 8.15.0
224 silly fetch manifest minimatch@^9.0.4
225 silly packumentCache full:https://registry.npmjs.org/minimatch cache-miss
226 http fetch GET 200 https://registry.npmjs.org/minimatch 2ms (cache hit)
227 silly packumentCache full:https://registry.npmjs.org/minimatch set size:398328 disposed:false
228 silly placeDep ROOT @typescript-eslint/visitor-keys@8.15.0 OK for: @typescript-eslint/scope-manager@8.15.0 want: 8.15.0
229 silly fetch manifest eslint-visitor-keys@^4.2.0
230 silly packumentCache full:https://registry.npmjs.org/eslint-visitor-keys cache-miss
231 http fetch GET 200 https://registry.npmjs.org/eslint-visitor-keys 1ms (cache hit)
232 silly packumentCache full:https://registry.npmjs.org/eslint-visitor-keys set size:61534 disposed:false
233 silly placeDep node_modules/@typescript-eslint/typescript-estree minimatch@9.0.5 OK for: @typescript-eslint/typescript-estree@8.15.0 want: ^9.0.4
234 silly fetch manifest brace-expansion@^2.0.1
235 silly packumentCache full:https://registry.npmjs.org/brace-expansion cache-miss
236 http fetch GET 200 https://registry.npmjs.org/brace-expansion 3ms (cache hit)
237 silly packumentCache full:https://registry.npmjs.org/brace-expansion set size:42345 disposed:false
238 silly placeDep node_modules/@typescript-eslint/visitor-keys eslint-visitor-keys@4.2.0 OK for: @typescript-eslint/visitor-keys@8.15.0 want: ^4.2.0
239 silly placeDep ROOT @eslint-react/ast@1.16.2 OK for: eslint-plugin-react-debug@1.16.2 want: 1.16.2
240 silly placeDep ROOT @eslint-react/core@1.16.2 OK for: eslint-plugin-react-debug@1.16.2 want: 1.16.2
241 silly placeDep ROOT @eslint-react/jsx@1.16.2 OK for: eslint-plugin-react-debug@1.16.2 want: 1.16.2
242 silly placeDep ROOT @eslint-react/var@1.16.2 OK for: eslint-plugin-react-debug@1.16.2 want: 1.16.2
243 silly placeDep node_modules/eslint-plugin-react-debug @typescript-eslint/type-utils@8.15.0 OK for: eslint-plugin-react-debug@1.16.2 want: ^8.15.0
244 silly placeDep ROOT string-ts@2.2.0 OK for: eslint-plugin-react-debug@1.16.2 want: ^2.2.0
245 silly placeDep ROOT ts-pattern@5.5.0 OK for: eslint-plugin-react-debug@1.16.2 want: ^5.5.0
246 silly fetch manifest short-unique-id@^5.2.0
247 silly packumentCache full:https://registry.npmjs.org/short-unique-id cache-miss
248 http fetch GET 200 https://registry.npmjs.org/short-unique-id 2ms (cache hit)
249 silly packumentCache full:https://registry.npmjs.org/short-unique-id set size:153077 disposed:false
250 silly placeDep ROOT birecord@0.1.1 OK for: @eslint-react/ast@1.16.2 want: ^0.1.1
251 verbose stack Error: Unable to resolve reference $eslint
251 verbose stack     at get spec (/opt/homebrew/Cellar/node@22/22.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/edge.js:202:15)
251 verbose stack     at #nodeFromEdge (/opt/homebrew/Cellar/node@22/22.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1039:46)
251 verbose stack     at #loadPeerSet (/opt/homebrew/Cellar/node@22/22.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1297:35)
251 verbose stack     at #nodeFromEdge (/opt/homebrew/Cellar/node@22/22.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1082:29)
251 verbose stack     at async #buildDepStep (/opt/homebrew/Cellar/node@22/22.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:904:11)
251 verbose stack     at async Arborist.buildIdealTree (/opt/homebrew/Cellar/node@22/22.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:181:7)
251 verbose stack     at async Promise.all (index 1)
251 verbose stack     at async Arborist.reify (/opt/homebrew/Cellar/node@22/22.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
251 verbose stack     at async Install.exec (/opt/homebrew/Cellar/node@22/22.11.0/lib/node_modules/npm/lib/commands/install.js:150:5)
251 verbose stack     at async Npm.exec (/opt/homebrew/Cellar/node@22/22.11.0/lib/node_modules/npm/lib/npm.js:207:9)
252 error Unable to resolve reference $eslint
253 silly unfinished npm timer reify 1732093433239
254 silly unfinished npm timer reify:loadTrees 1732093433239
255 silly unfinished npm timer idealTree:buildDeps 1732093433408
256 silly unfinished npm timer idealTree:node_modules/@eslint-react/core 1732093434179
257 verbose cwd /Users/rakleed/Developer/react-crm-app
258 verbose os Darwin 24.1.0
259 verbose node v22.11.0
260 verbose npm  v10.9.0
261 verbose exit 1
262 verbose code 1
263 error A complete log of this run can be found in: /Users/rakleed/.npm/_logs/2024-11-20T09_03_53_125Z-debug-0.log
```

</details>

## Expected Behavior

In `package.json` the dependencies are updated and installed without errors.

**Comment by raineorshine** [comment]
Hi, thanks for reporting.

Related: #1332

**Comment by XhmikosR** [comment]
It seems this issue is fixed upstream, @rakleed can you confirm?
