### ISSUE TITLE
Unseen selection at the top of the list causes error

### ISSUE THREAD

**Issue by ajuvonen** [raineorshine/npm-check-updates#1484]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)

---

## Steps to Reproduce

Dependencies:

Running Node 22.11 on a Windows 11 machine and Git Bash

Steps:

1. Have ncu installed globally
2. Run `ncu -i`
3. With the provided list, press up key once. Notice the cursor disappears.
4. Press space bar
5. Move cursor back down and de-select all items
6. Press enter

## Current Behavior

TypeError: Cannot read properties of undefined (reading 'replace')
    at kX ([path-to-node]\v22.11.0\node_modules\npm-check-updates\build\index.js:450:2588)
    at [path-to-node]\v22.11.0\node_modules\npm-check-updates\build\index.js:450:2835
    at Array.forEach (<anonymous>)
    at [path-to-node]\v22.11.0\node_modules\npm-check-updates\build\index.js:450:2774
    at String.replace (<anonymous>)
    at G2 ([path-to-node]\v22.11.0\node_modules\npm-check-updates\build\index.js:450:2745)
    at Cw ([path-to-node]\v22.11.0\node_modules\npm-check-updates\build\index.js:545:597)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async yse ([path-to-node]\v22.11.0\node_modules\npm-check-updates\build\index.js:547:750)

## Expected Behavior

Cursor should move to the end of the list when moving upwards from the start of the list. Upon completion, there should be no error but a notification that no dependencies were updated.

**Comment by raineorshine** [comment]
Hi, thanks for reporting!

Identified and fixed in `v17.1.13`.
