### ISSUE TITLE
FontAwesome Pro: authentication method is no longer supported

### ISSUE THREAD

**Issue by tcastelly** [raineorshine/npm-check-updates#649]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 12.14.1
* npm version: 6.13.4
* npm-check-updates version: 4.1.2

---------------------------

"this authentication method is no longer supported."

```
[=-------------------] 3/45 6%~/.config/yarn/global/node_modules/npm-check-updates/lib/npm-check-updates.js:412
    throw err;
    ^

HttpErrorGeneral: 403 Forbidd~s://npm.fontawesome.com/XXXX/@fortawesome%2ffontawesome-svg-core - Hit the brakes, Ricky Bobby: this authentication method is no longer supported. Take a pit stop and read the docs to continue. https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro
    at /home/shenron/.config/yarn/global/node_modules/npm-registry-fetch/check-response.js:110:15
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async /home/shenron/.config/yarn/global/node_modules/p-map/index.js:57:22 {
  headers: [Object: null prototype] {
    'content-type': [ 'application/json' ],
    'content-length': [ '239' ],
    connection: [ 'keep-alive' ],
    server: [ 'CloudFront' ],
    date: [ 'Thu, 23 Apr 2020 15:40:09 GMT' ],
    'x-cache': [ 'LambdaGeneratedResponse from cloudfront' ],
    via: [
      '1.1 8a399dda74d3b3eb108151355b396179.cloudfront.net (CloudFront)'
    ],
    'x-amz-cf-pop': [ 'CDG3-C1' ],
    'x-amz-cf-id': [ 'NF34BlV3kC0B9mb1pSmrUsFIDhIwMRegp7OMZuOoeB3Q98VyauwkKg==' ],
    'x-fetch-attempts': [ '1' ]
  },
  statusCode: 403,
  code: 'E403',
  method: 'GET',
  uri: 'https://npm.fontawesome.com/XXXX/@fortawesome%2ffontawesome-svg-core',
  body: {
    ok: false,
    error: 'Hit the brakes, Ricky Bobby: this authentication method is no longer supported. Take a pit stop and read the docs to continue. https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro'
  },
  pkgid: '@fortawesome/fontawesome-svg-core@latest',
  message: '403 Forbidden - GET https://npm.fontawesome.com/XXXX/@fortawesome%2ffontawesome-svg-core - Hit the brakes, Ricky Bobby: this authentication method is no longer supported. Take a pit stop and read the docs to continue. https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro'
}
```

I use this command just to escape @forawesome
>  ncu -u '/^(?!@fortawesome).*$/'

**Comment by stoically** [comment]
Maybe the referenced docs in the error message have relevant information? https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro

**Comment by tcastelly** [comment]
Thank you for the answer. 

I did this, and I can install properly the dependency. The problem is only when I use `npm-check-updates`

**Comment by stoically** [comment]
Ah, I see. The combination of `libnpmconfig` and `pacote`, which ncu uses, probably doesn't support that kind of tying an registry to an  "@-scope" yet.

**Comment by raineorshine** [comment]
Closing as this is likely related to `pacote`. If `pacote packument` is confirmed working and an `npm-check-updates` test case can be produced I will re-open. Thanks!
