### ISSUE TITLE
Error updating from 4.0.1 to 7.0.1: SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by borgogelli** [raineorshine/npm-check-updates#695]
After updating from 4.0.1 to 7.0.1
```
$ node  -v
v8.10.0
$ npm -v
6.14.6
```

`$ ncu -g`

The output is:

```
/usr/local/lib/node_modules/npm-check-updates/node_modules/get-stdin/index.js:13
        for await (const chunk of stdin) {
            ^^^^^

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:13:18)
```

**Comment by raineorshine** [comment]
Why did you delete the issue template? It's there for a good reason :).

> - [ ] I am using `node >= 10.17`

`ncu` now requires `node >= 10.17`.

**Comment by borgogelli** [comment]
@raineorshine thank you, sometime I'm irrational :-)
