### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by Davesmarth** [raineorshine/npm-check-updates#776]
**I tried to run the 'ncu -u' command and it throws me this error**

/usr/local/lib/node_modules/npm-check-updates/node_modules/update-notifier/index.js:58
			} catch {
			        ^

SyntaxError: Unexpected token 
at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/node_modules/find-up/index.js:3:20)

**Comment by raineorshine** [comment]
Technically the error is in `update-notifier`, but it seems like you may be using an old version of `node`. Can you confirm? `npm-check-updates` requires `>=10.17`.

(Please don't delete issue templates when you file an issue on an open source library. They're an important part of the troubleshooting process.)

**Comment by Davesmarth** [comment]
you were right, when I installed `node js` I didn't realize an old version had been installed, thank you so much.
