### ISSUE TITLE
TypeError: Invalid Version: 723

### ISSUE THREAD

**Issue by drmrbrewer** [raineorshine/npm-check-updates#830]
I'm getting the above error, with the relevant info below:

	# ncu -u
	Upgrading /root/workspace/myapp/package.json
	[====================] 28/28 100%
	/root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/lib/index.js:377
	  throw err
	  ^

	TypeError: Invalid Version: 723
		at new SemVer (/root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/node_modules/semver/classes/semver.js:38:13)
		at outside (/root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/node_modules/semver/ranges/outside.js:12:13)
		at Object.ltr (/root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/node_modules/semver/ranges/ltr.js:3:42)
		at isUpgradeable (/root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/lib/versionmanager.js:120:17)
		at /root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/lib/versionmanager.js:65:67
		at /root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:13616:16
		at basePickBy (/root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:3783:13)
		at Function.pickBy (/root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:13615:14)
		at /root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:4388:28
		at arrayReduce (/root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:683:21)
		
	# ncu --version
	11.1.4

Content of `package.json`:

	"dependencies": {
		...
		"mylibrary": "git+https://myusername:jfF8aS2d9fkasdLASD09@bitbucket.org/myusername/mylibrary.git#v723",
		...
	}

Whilst a version name of `v723` is non-standard, it was explicitly allowed previously in ncu... see [here](https://github.com/raineorshine/npm-check-updates/issues/747#issuecomment-715507704).

EDIT it works in `11.1.3`... only broke in `11.1.4`.

**Comment by raineorshine** [comment]
Thanks! I'll look into it.

**Comment by raineorshine** [comment]
Could you run `ncu --loglevel verbose` please?

**Comment by drmrbrewer** [comment]
# ncu --loglevel verbose
	Initializing
	Running in local mode
	Finding package file data
	Checking /root/workspace/myapp/package.json
	Fetching latest versions

	Options:
	{
	  args: [],
	  bundle: true,
	  cli: true,
	  concurrency: 8,
	  deep: false,
	  dev: true,
	  errorLevel: 1,
	  format: [],
	  json: false,
	  loglevel: 'verbose',
	  minimal: false,
	  optional: true,
	  packageManager: 'npm',
	  peer: true,
	  prefix: null,
	  prod: true,
	  target: 'latest',
	  version: '11.1.4'
	}
	[====================] 28/28 100%
	/root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/lib/index.js:377
	  throw err
	  ^

	TypeError: Invalid Version: 723
		at new SemVer (/root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/node_modules/semver/classes/semver.js:38:13)
		at outside (/root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/node_modules/semver/ranges/outside.js:12:13)
		at Object.ltr (/root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/node_modules/semver/ranges/ltr.js:3:42)
		at isUpgradeable (/root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/lib/versionmanager.js:120:17)
		at /root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/lib/versionmanager.js:65:67
		at /root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:13658:16
		at basePickBy (/root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:3825:13)
		at Function.pickBy (/root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:13657:14)
		at /root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:4430:28
		at arrayReduce (/root/.nvm/versions/node/v14.15.5/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:697:21)

**Comment by raineorshine** [comment]
I created a private BitBucket repository to try to reproduce, but unfortunately I was getting auth errors for some reason.

npm-check-updates uses [parse-github-url](https://github.com/jonschlinkert/parse-github-url) to parse all git urls (despite the name "github"). I wonder if it's not parsing your url properly.

Could you try running this in an empty directory and let me know what you get (blanking out credentials as needed)?

```sh
npm install --save parse-github-url
node -e "console.log(require('parse-github-url')('git+https://myusername:jfF8aS2d9fkasdLASD09@bitbucket.org/myusername/mylibrary.git#v723'))" | c
```

**Comment by drmrbrewer** [comment]
Here you go (replacing credentials with the dummy ones used in the example):

	# node -e "console.log(require('parse-github-url')('git+https://myusername:jfF8aS2d9fkasdLASD09@bitbucket.org/myusername/mylibrary.git#v723'))"
	Url {
	  protocol: 'git+https:',
	  slashes: true,
	  auth: 'myusername:jfF8aS2d9fkasdLASD09',
	  host: 'bitbucket.org',
	  port: null,
	  hostname: 'bitbucket.org',
	  hash: '#v723',
	  search: null,
	  query: null,
	  pathname: 'myusername/mylibrary.git',
	  path: 'myusername/mylibrary.git',
	  href: 'git+https://myusername:jfF8aS2d9fkasdLASD09@bitbucket.org/myusername/mylibrary.git#v723',
	  filepath: null,
	  owner: 'myusername',
	  name: 'common',
	  repo: 'myusername/mylibrary',
	  branch: 'v723',
	  repository: 'myusername/mylibrary'
	}

**Comment by raineorshine** [comment]
Could you try ncu `v11.1.8`? I manually tested version `723` and made sure that `versionUtil.isSimple` could handle it.

**Comment by drmrbrewer** [comment]
Works!  🎉🎉
