### ISSUE TITLE
TypeError: Invalid Version: 1.4

### ISSUE THREAD

**Issue by exytab** [raineorshine/npm-check-updates#915]
I'm getting the above error, with the relevant info below: 

```
PS C:\_\inx\src\ui\Inx.Web.UI> ncu --loglevel verbose
Initializing
Running in local mode
Finding package file data
Checking C:\_\inx\src\ui\Inx.Web.UI\package.json
Fetching latest versions

Options:
{
  args: [],
  cli: true,
  concurrency: 8,
  deep: false,
  errorLevel: 1,
  format: [],
  json: false,
  loglevel: 'verbose',
  minimal: false,
  packageManager: 'npm',
  prefix: null,
  target: 'latest',
  version: '11.7.1'
}
C:\Users\myexy\AppData\Roaming\npm\node_modules\npm-check-updates\lib\index.js:425
  throw err
  ^

TypeError: Invalid Version: 1.4
    at new SemVer (C:\Users\myexy\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\semver\classes\semver.js:38:13)
    at outside (C:\Users\myexy\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\semver\ranges\outside.js:12:13)
    at Object.ltr (C:\Users\myexy\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\semver\ranges\ltr.js:3:42)
    at isUpgradeable (C:\Users\myexy\AppData\Roaming\npm\node_modules\npm-check-updates\lib\versionmanager.js:121:17)
    at C:\Users\myexy\AppData\Roaming\npm\node_modules\npm-check-updates\lib\versionmanager.js:66:67
    at C:\Users\myexy\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\lodash\lodash.js:13658:16
    at basePickBy (C:\Users\myexy\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\lodash\lodash.js:3825:13)
    at Function.pickBy (C:\Users\myexy\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\lodash\lodash.js:13657:14)
    at C:\Users\myexy\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\lodash\lodash.js:4430:28
    at arrayReduce (C:\Users\myexy\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\lodash\lodash.js:697:21)
```

- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues/830)
- [x] I am using the latest version of `npm-check-updates` (11.7.1)  
- [x] I am using `node >= 10.17` (v14.17.0)  

package.json: 
```
{
"dependencies": {
    "@emotion/css": "11.1.3",
    "@emotion/server": "11.4.0",
    "@formatjs/intl-relativetimeformat": "9.1.6",
    "@microsoft/signalr": "5.0.7",
    "ace-builds": "1.4.12",
    "assign-deep": "1.0.1",
    "awesome-bootstrap-checkbox": "0.3.7",
    "balloon-css": "1.2.0",
    "bootstrap-sass": "3.4.1",
    "camelcase": "6.2.0",
    "classnames": "2.3.1",
    "content-disposition": "0.5.3",
    "d3-scale-chromatic": "2.0.0",
    "dexie": "3.0.3",
    "file-saver": "2.0.5",
    "filesize": "6.3.0",
    "font-awesome": "4.7.0",
    "history": "4.10.1",
    "intl-messageformat": "9.7.0",
    "invariant": "2.2.4",
    "isobject": "3.0.1",
    "js-beautify": "1.14.0",
    "jsnlog": "2.30.0",
    "lodash": "4.17.21",
    "memoize-one": "5.2.1",
    "moment": "2.29.1",
    "numbro": "2.3.2",
    "path-browserify": "1.0.1",
    "path-to-regexp": "6.2.0",
    "query-string": "7.0.1",
    "quill": "1.3.7",
    "react": "16.14.0",
    "react-ace": "9.4.1",
    "react-beautiful-dnd": "13.1.0",
    "react-bootstrap": "exytab/react-bootstrap#v0.33",
    "react-clipboard.js": "2.0.16",
    "react-datepicker": "4.1.1",
    "react-dates": "21.8.0",
    "react-dnd": "11.1.3",
    "react-dnd-html5-backend": "11.1.3",
    "react-dom": "16.14.0",
    "react-highlight-words": "0.17.0",
    "react-intl": "5.20.3",
    "react-loading": "2.0.3",
    "react-number-format": "4.6.3",
    "react-onclickoutside": "6.11.2",
    "react-quill": "1.3.5",
    "react-redux": "7.2.4",
    "react-redux-loading-bar": "5.0.0",
    "react-router": "5.2.0",
    "react-router-dom": "5.2.0",
    "react-select": "4.1.0",
    "react-sortable-tree": "2.8.0",
    "react-virtualized": "9.22.3",
    "recharts": "2.0.9",
    "redux": "4.1.0",
    "redux-logger": "3.0.6",
    "reselect": "4.0.0",
    "simple-line-icons": "2.5.5",
    "warning": "4.0.3",
    "whatwg-fetch": "3.6.2"
  },
  "devDependencies": {
    "@babel/cli": "7.14.5",
    "@babel/core": "7.14.6",
    "@babel/plugin-proposal-object-rest-spread": "7.14.7",
    "@babel/plugin-transform-flow-strip-types": "7.14.5",
    "@babel/plugin-transform-regenerator": "7.14.5",
    "@babel/plugin-transform-runtime": "7.14.5",
    "@babel/preset-env": "7.14.7",
    "@babel/preset-react": "7.14.5",
    "@emotion/babel-plugin": "11.3.0",
    "@emotion/eslint-plugin": "11.2.0",
    "@storybook/addon-actions": "6.3.0",
    "@storybook/addon-console": "1.2.3",
    "@storybook/addons": "6.3.0",
    "@storybook/react": "6.3.0",
    "@types/content-disposition": "0.5.3",
    "@types/d3-scale-chromatic": "2.0.0",
    "@types/enzyme": "3.10.8",
    "@types/file-saver": "2.0.2",
    "@types/invariant": "2.2.34",
    "@types/jest": "26.0.23",
    "@types/js-beautify": "1.13.1",
    "@types/lodash": "4.14.170",
    "@types/react": "16.14.2",
    "@types/react-beautiful-dnd": "13.0.0",
    "@types/react-bootstrap": "0.32.25",
    "@types/react-datepicker": "3.1.8",
    "@types/react-dates": "21.8.2",
    "@types/react-dom": "16.9.10",
    "@types/react-highlight-words": "0.16.2",
    "@types/react-onclickoutside": "6.7.3",
    "@types/react-redux": "7.1.16",
    "@types/react-router": "5.1.15",
    "@types/react-router-dom": "5.1.7",
    "@types/react-select": "4.0.15",
    "@types/react-sortable-tree": "0.3.13",
    "@types/react-test-renderer": "16.9.4",
    "@types/redux-logger": "3.0.8",
    "@types/warning": "3.0.0",
    "@typescript-eslint/eslint-plugin": "4.28.0",
    "@typescript-eslint/parser": "4.28.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "10.1.0",
    "babel-jest": "27.0.5",
    "babel-loader": "8.2.2",
    "babel-plugin-jsx-control-statements": "4.1.0",
    "case-sensitive-paths-webpack-plugin": "2.4.0",
    "chokidar": "3.5.2",
    "circular-dependency-plugin": "5.2.2",
    "core-js": "3.15.1",
    "css-loader": "5.2.6",
    "enzyme": "3.11.0",
    "enzyme-adapter-react-16": "1.15.6",
    "eslint": "7.29.0",
    "eslint-config-eslint": "7.0.0",
    "eslint-plugin-import": "2.23.4",
    "eslint-plugin-jest": "24.3.6",
    "eslint-plugin-jsx-a11y": "6.4.1",
    "eslint-plugin-jsx-control-statements": "2.2.1",
    "eslint-plugin-react": "7.24.0",
    "eslint-plugin-react-hooks": "4.2.0",
    "espree": "7.3.1",
    "expose-loader": "3.0.0",
    "hjson": "3.2.2",
    "increase-memory-limit": "1.0.7",
    "jest": "27.0.5",
    "jest-enzyme": "7.1.2",
    "nock": "13.1.0",
    "node-sass": "6.0.1",
    "react-test-renderer": "16.14.0",
    "redux-mock-store": "1.5.4",
    "regenerator-runtime": "0.13.7",
    "resize-observer-polyfill": "1.5.1",
    "sass-loader": "12.1.0",
    "style-loader": "2.0.0",
    "thread-loader": "3.0.4",
    "ts-jest": "27.0.3",
    "ts-loader": "9.2.3",
    "tsconfig-paths-webpack-plugin": "3.5.1",
    "typescript": "4.3.4",
    "url-search-params-polyfill": "8.1.1",
    "webpack": "5.40.0",
    "webpack-bundle-analyzer": "4.4.2",
    "webpack-cli": "4.7.2",
    "webpack-dev-middleware": "5.0.0",
    "webpack-merge": "5.8.0"
  }
}
```

**Comment by raineorshine** [comment]
One of your dependencies has published an invalid semver version of "1.4".

That said, `npm-check-updates` does attempt to handle some such "pseudo versions", there was just a bug in the implementation.

Can you try `v11.8.0` and see if it fixed it for you?

**Comment by exytab** [comment]
@raineorshine thanks!  
`v11.8.0` fixed it!

**Comment by raineorshine** [comment]
FYI This is the dependency that uses an invalid semver version:

```json
    "react-bootstrap": "exytab/react-bootstrap#v0.33",
```
