### ISSUE TITLE
Expected JSON from "npm ls". This could be due to npm instability.

### ISSUE THREAD

**Issue by akornatskyy** [raineorshine/npm-check-updates#939]
OS: Windows 10
node: v16.8.0
npm: 7.21.0
ncu: 11.8.3

Steps to reproduce:

```sh
ncu -g
```

It works as expected with local checks.

**Comment by raineorshine** [comment]
Thanks for reporting. Can you post the full error message? It contains the response that came back from `npm ls --json`.

**Comment by akornatskyy** [comment]
`npm ls --json`:
```
{}
```

Stack trace:

```
...AppData\Roaming\npm\node_modules\npm-check-updates\lib\index.js:425
  throw err
  ^

Error: Expected JSON from "npm ls". This could be due to npm instability.


    at parseJson (...\AppData\Roaming\npm\node_modules\npm-check-updates\lib\package-managers\npm.js:76:11)
    at Object.list (...\AppData\Roaming\npm\node_modules\npm-check-updates\lib\package-managers\npm.js:284:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.getInstalledPackages (...\AppData\Roaming\npm\node_modules\npm-check-updates\lib\versionmanager.js:382:22)
    at async analyzeGlobalPackages (...\AppData\Roaming\npm\node_modules\npm-check-updates\lib\index.js:81:26)
    at async getAnalysis (...\AppData\Roaming\npm\node_modules\npm-check-updates\lib\index.js:504:24)
```

**Comment by raineorshine** [comment]
It looks like your npm is not returning any response. Do you get the same thing when you run `npm -g ls --json` on the command line?

**Comment by akornatskyy** [comment]
appologies, forgot to add `-g` there. `npm -g ls --json`:
```
npm ERR! Cannot set property 'peer' of null
{
  "error": {
    "code": null,
    "summary": "Cannot set property 'peer' of null",
    "detail": ""
  }
}
```
debug.log:
```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   '-g',
0 verbose cli   'ls',
0 verbose cli   '--json'
0 verbose cli ]
1 info using npm@7.21.0
2 info using node@v16.8.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 verbose config optional Use `--omit=optional` to exclude optional dependencies, or
11 verbose config `--include=optional` to include them.
11 verbose config
11 verbose config     Default value does install optional deps unless otherwise omitted.
12 timing config:load:file:C:\Users\Andriy_Kornatskyy\.npmrc Completed in 1ms
13 timing config:load:user Completed in 1ms
14 timing config:load:file:C:\Users\andriy_kornatskyy\AppData\Roaming\npm\etc\npmrc Completed in 0ms
15 timing config:load:global Completed in 0ms
16 timing config:load:validate Completed in 1ms
17 timing config:load:credentials Completed in 0ms
18 timing config:load:setEnvs Completed in 1ms
19 timing config:load Completed in 10ms
20 timing npm:load:configload Completed in 10ms
21 timing npm:load:setTitle Completed in 0ms
22 timing npm:load:setupLog Completed in 1ms
23 timing config:load:flatten Completed in 2ms
24 timing npm:load:cleanupLog Completed in 2ms
25 timing npm:load:configScope Completed in 0ms
26 timing npm:load:projectScope Completed in 0ms
27 timing npm:load Completed in 17ms
28 timing arborist:ctor Completed in 1ms
29 timing command:ls Completed in 416ms
30 verbose stack TypeError: Cannot set property 'peer' of null
30 verbose stack     at visit (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\calc-dep-flags.js:96:54)
30 verbose stack     at visitNode (C:\Program Files\nodejs\node_modules\npm\node_modules\treeverse\lib\depth-descent.js:57:25)
30 verbose stack     at next (C:\Program Files\nodejs\node_modules\npm\node_modules\treeverse\lib\depth-descent.js:44:19)
30 verbose stack     at depth (C:\Program Files\nodejs\node_modules\npm\node_modules\treeverse\lib\depth-descent.js:82:10)
30 verbose stack     at depth (C:\Program Files\nodejs\node_modules\npm\node_modules\treeverse\lib\depth.js:27:12)
30 verbose stack     at unsetFlag (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\calc-dep-flags.js:91:5)
30 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\calc-dep-flags.js:63:7
30 verbose stack     at Map.forEach (<anonymous>)
30 verbose stack     at calcDepFlagsStep (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\calc-dep-flags.js:40:17)
30 verbose stack     at visit (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\calc-dep-flags.js:12:20)
31 verbose cwd C:\
32 verbose Windows_NT 10.0.19042
33 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "-g" "ls" "--json"
34 verbose node v16.8.0
35 verbose npm  v7.21.0
36 error Cannot set property 'peer' of null
37 verbose exit 1
```

**Comment by raineorshine** [comment]
Looks like you've got a problem `npm`, not `npm-check-updates`. I recommend opening an issue with npm.

**Comment by akornatskyy** [comment]
Opened issue [3711](https://github.com/npm/cli/issues/3711) with npm. You might consider to print npm output directly in case you cannot parse it.
